name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint ruff

      - name: Lint (ruff)
        run: |
          ruff --version || true
          ruff check . || true

      - name: Lint (pylint)
        run: |
          pylint $(git ls-files '*.py') || true

      - name: Run tests (pytest)
        env:
          EMBEDDINGS_PROVIDER: mock
          TELEGRAM_TOKEN: dummy
        run: |
          make test


